# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-08 21:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('saldo', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Quantidade de Produtos')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='fornecedor/')),
            ],
        ),
        migrations.CreateModel(
            name='IncluirFornecedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produtosanterior', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Quantidade de Produtos anterior')),
                ('quantidade', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Quantidade')),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='livros.Fornecedor')),
            ],
        ),
    ]
