# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-08 23:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0002_auto_20160508_1819'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='livro',
            options={'verbose_name': 'Livro', 'verbose_name_plural': 'Livros'},
        ),
        migrations.RemoveField(
            model_name='emprestimolivro',
            name='produtosanterior',
        ),
        migrations.RemoveField(
            model_name='emprestimolivro',
            name='quantidade',
        ),
        migrations.AddField(
            model_name='emprestimolivro',
            name='escola',
            field=models.CharField(default=1, max_length=40, verbose_name='Escola'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emprestimolivro',
            name='matricula',
            field=models.DecimalField(decimal_places=0, default=1, max_digits=20, verbose_name='Matricula'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emprestimolivro',
            name='nome',
            field=models.CharField(default=1, max_length=40, verbose_name='Nome'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='livro',
            name='numero',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='N\xfamero do livro'),
        ),
        migrations.AlterField(
            model_name='livro',
            name='titulo',
            field=models.CharField(max_length=40, verbose_name='T\xedtulo'),
        ),
    ]
