# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-08 23:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0003_auto_20160508_2035'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='autor',
            field=models.CharField(default=1, max_length=20, verbose_name='T\xedtulo'),
            preserve_default=False,
        ),
    ]
