# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-08 23:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0004_livro_autor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimolivro',
            name='matricula',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=20, verbose_name='Matricula'),
        ),
        migrations.AlterField(
            model_name='livro',
            name='foto',
            field=models.ImageField(blank=True, default='livro/default.jpg', null=True, upload_to='livro/'),
        ),
    ]
