# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-09 00:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0005_auto_20160508_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='autor',
            field=models.CharField(max_length=20, verbose_name='Autor'),
        ),
    ]
