# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-18 02:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postagens', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comentario',
            options={'verbose_name': 'Comentario', 'verbose_name_plural': 'Comentarios'},
        ),
        migrations.AddField(
            model_name='postar',
            name='data_publicacao',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
