# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-18 15:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postagens', '0002_auto_20160417_2353'),
    ]

    operations = [
        migrations.AddField(
            model_name='postar',
            name='foto',
            field=models.ImageField(blank=True, max_length=255, upload_to=b'contato/%Y', verbose_name=b'Foto'),
        ),
    ]
