# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-11 00:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postagens', '0003_postar_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postar',
            name='foto',
            field=models.ImageField(blank=True, max_length=255, upload_to=b'imagens_noticias/', verbose_name=b'Foto'),
        ),
    ]
